iranian_months:
  farvardin: "فروردین"
  ordibehesht: "اردیبهشت"
  khordad: "خرداد"
  tir: "تیر"
  mordad: "مرداد"
  shahrivar: "شهریور"
  mehr: "مهر"
  aban: "آبان"
  azar: "آذر"
  dey: "دی"
  bahman: "بهمن"
  esfand: "اسفند"